config/routes.rb
Rails.application.routes.draw do
  root to: 'games#index'

  resources :games, except: [:update, :edit, :destroy]
end

app/models/frame.rb
class Frame < ActiveRecord::Base
  belongs_to :game

  serialize :bonus_shots, Array

  before_save :normalize_values

  def strike?
    self.first_ball == 10
  end

  def spare?
    !self.strike? && (self.score) == 10
  end

  def score
    self.first_ball + self.second_ball + self.bonus_shots.inject(0, :+)
  end

  private
    def normalize_values
      self.first_ball = 0 if self.first_ball.to_i > 10
      self.second_ball = 0 if self.second_ball.to_i > 10
    end
end

app/models/game.rb
class Game < ActiveRecord::Base
  validates :name, presence: true

  has_many :frames
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    @score = ScoreCalculator.new(@game).calculate
  end

  def new
    @game = Game.new
  end

  def create
    @frame_loader = FrameLoader.new(games_params)
    if @frame_loader.parse
      redirect_to @frame_loader.game
    end
  end

  private
    def games_params
      params.require(:game).permit(:name, :pins)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.haml
%table
  %tr
    %th Game Name
  - @games.each do |game|
    %tr
      %td= link_to "#{game.name}", game_path(game)

= link_to 'Create New Game', new_game_path

app/views/games/new.html.haml
= form_for @game do |f|
  = f.label :name
  = f.text_field :name

  = f.label "Scores"
  = text_field_tag "game[pins]"

  = f.submit

app/views/games/show.html.haml
%h1 #{@game.name}

%table
  %tr
    %th number
    %th First ball
    %th Second ball
  - @game.frames.each do |frame|
    %tr
      %td #{frame.number}
      %td #{frame.first_ball}
      %td #{frame.second_ball}

%h2 Total Score: #{@score}

= link_to 'Back', games_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RubyTEst
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield